### ISSUE TITLE
Lawson iteration and sample weights

### ISSUE THREAD

**Issue by gridley** [c-f-h/aaa#2]
I'd like to propose adding weights to the sample points, which was discussed in the original AAA paper. It's very easy to do.

With this, the extra Lawson iteration step at the end to reduce the error further while not adding extra barycentric terms is straightforward to add.

Would you want a PR for this @c-f-h ?

**Comment by c-f-h** [comment]
Hi @gridley,

That sounds very useful, but this repository is no longer maintained. Please submit a PR to the https://github.com/c-f-h/baryrat/ repository where the most up to date version of the AAA implementation is kept.

**Comment by gridley** [comment]
Sorry about that! I meant to go to the other repo.

Gotcha. I will certainly do that at some point, then.
